/* =============================================================
   HAPAG — static data module.
   Recipes are shipped with the app: lookups resolve in <1ms,
   which is why no loading state exists anywhere in this UI.
   ============================================================= */

export const CATEGORIES = ["Stew", "Soup", "Beef", "Pork", "Chicken", "Seafood", "Vegetable"]

export const SKILL_LEVELS = ["All", "Beginner", "Intermediate", "Advanced"]

/**
 * Kiosk-mode categories — Filipino cooking-method names.
 * Each entry has a label (shown in the sidebar) and a filter predicate.
 */
export const KIOSK_CATEGORIES = [
  { key: "ALL",       label: "ALL" },
  { key: "SABAW",     label: "SABAW" },
  { key: "GISA",      label: "GISA" },
  { key: "PRITO",     label: "PRITO" },
  { key: "INIHAW",    label: "INIHAW" },
  { key: "GULAY",     label: "GULAY" },
  { key: "MINATAMIS", label: "MINATAMIS" },
  { key: "SARI_SARI", label: "SARI-SARI" },
]

/** Maps a kiosk category key to a predicate that filters VIANDS. */
export const KIOSK_CAT_FILTER = {
  ALL:       () => true,
  SABAW:     (v) => v.cats.includes("Soup"),
  GISA:      (v) => v.cats.includes("Stew"),
  PRITO:     (v) => v.cats.includes("Pork") || v.cats.includes("Chicken") || v.id === 18,
  INIHAW:    (v) => v.id === 16 || v.cats.includes("Beef"),
  GULAY:     (v) => v.cats.includes("Vegetable"),
  MINATAMIS: (v) => v.cats.includes("Dessert") || v.cats.includes("Sweet") || v.id === 20,
  SARI_SARI: () => true,
}


export const INGREDIENT_GROUPS = {
  Protein: [
    "Chicken",
    "Pork",
    "Beef",
    "Pork Belly",
    "Ground Pork",
    "Bacon",
    "Tilapia",
    "Bangus",
    "Shrimp",
    "Squid",
    "Crab",
    "Egg",
    "Tofu",
  ],
  Vegetable: [
    "Kangkong",
    "Sitaw (String Beans)",
    "Kalabasa (Squash)",
    "Ampalaya (Bitter Gourd)",
    "Sayote (Chayote)",
    "Cabbage",
    "Carrots",
    "Potato",
    "Eggplant",
    "Okra",
    "Malunggay",
    "Tomato",
    "Bell Pepper",
    "Corn",
    "Taro Leaves (Dahon ng Gabi)",
    "Radish",
  ],
  Pantry: [
    "Soy Sauce",
    "Vinegar",
    "Fish Sauce (Patis)",
    "Shrimp Paste (Bagoong)",
    "Oyster Sauce",
    "Coconut Milk (Gata)",
    "Tomato Sauce",
    "Tamarind (Sampalok)",
    "Peanut Butter",
    "Curry Powder",
    "Mung Beans (Monggo)",
  ],
  Aromatics: ["Onion", "Garlic", "Ginger", "Green Onion", "Siling Haba (Long Chili)", "Bay Leaf (Laurel)", "Calamansi"],
}

/** Ingredients every Filipino kitchen is assumed to have — never counted as missing. */
export const PANTRY_STAPLES = ["Salt", "Pepper", "Cooking Oil", "Sugar", "Water", "Rice"]

export const VIANDS = [
  {
    id: 1,
    name: "Chicken Adobo",
    fname: "Adobong Manok",
    cats: ["Chicken", "Stew"],
    diff: "Beginner",
    minutes: 50,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/filipino-chicken-adobo-recipe/",
    desc: "The quintessential Filipino stew — chicken braised in soy sauce, vinegar, and garlic until deeply savory and tender.",
    ing: ["Chicken", "Soy Sauce", "Vinegar", "Garlic", "Bay Leaf (Laurel)", "Onion"],
    ingredientsDetailed: [
      "2 lbs Chicken (cut into serving pieces)",
      "1/2 cup Soy Sauce",
      "1/3 cup Vinegar (cane or white)",
      "1 head Garlic (crushed)",
      "3 pcs Bay Leaf (Laurel)",
      "1 medium Onion (sliced)",
      "1 cup Water",
      "1 tsp Whole Peppercorns"
    ],
    steps: [
      "Combine chicken, soy sauce, and crushed garlic in a bowl. Marinate for at least 30 minutes.",
      "Heat cooking oil in a pan and sear chicken pieces for 2 to 3 minutes per side until lightly browned.",
      "Pour in vinegar, bay leaves, and remaining marinade with 1 cup water. Bring to a boil without stirring for 2 minutes.",
      "Lower heat, cover, and simmer for 25 to 30 minutes until chicken is tender.",
      "Uncover and simmer for 5 to 8 minutes until the sauce reduces and coats the chicken in a rich glaze. Serve hot over rice."
    ],
  },
  {
    id: 2,
    name: "Pork Adobo",
    fname: "Adobong Baboy",
    cats: ["Pork", "Stew"],
    diff: "Beginner",
    minutes: 60,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/pork-adobo-recipe/",
    desc: "Pork belly slow-braised in a vinegar and soy marinade until the fat renders rich and glossy.",
    ing: ["Pork Belly", "Soy Sauce", "Vinegar", "Garlic", "Bay Leaf (Laurel)", "Onion"],
    ingredientsDetailed: [
      "2 lbs Pork Belly (cut into 2-inch cubes)",
      "1/2 cup Soy Sauce",
      "1/3 cup Vinegar",
      "1 head Garlic (crushed)",
      "3 pcs Bay Leaf (Laurel)",
      "1 medium Onion (chopped)",
      "1 1/2 cups Water",
      "1 tsp Whole Peppercorns"
    ],
    steps: [
      "Marinate pork belly cubes in soy sauce and crushed garlic for 30 to 60 minutes.",
      "Heat a pot and sear the marinated pork belly until golden brown and natural oils render.",
      "Pour in vinegar and bay leaves. Bring to a boil over medium heat without stirring for 3 minutes.",
      "Pour in reserved marinade and water. Cover and simmer on low heat for 40 to 45 minutes until fork-tender.",
      "Uncover and simmer until sauce is reduced, thick, and coats each pork piece."
    ],
  },
  {
    id: 3,
    name: "Sinigang na Baboy",
    fname: "Pork Sinigang",
    cats: ["Pork", "Soup"],
    diff: "Beginner",
    minutes: 70,
    serves: 6,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Sinigang+na+Baboy",
    desc: "A comforting sour tamarind broth loaded with tender pork belly or ribs, eggplant, okra, sitaw, radish, and fresh kangkong.",
    ing: [
      "Pork Belly",
      "Tamarind (Sampalok)",
      "Tomato",
      "Onion",
      "Sitaw (String Beans)",
      "Kangkong",
      "Radish",
      "Eggplant",
      "Okra",
      "Siling Haba (Long Chili)",
      "Fish Sauce (Patis)",
    ],
    ingredientsDetailed: [
      "2 lbs Pork Belly (or spare ribs, sliced into serving pieces)",
      "1 pack (44g) Knorr Sinigang sa Sampaloc Mix",
      "8 cups Water",
      "2 medium Tomatoes (quartered)",
      "1 medium Onion (quartered)",
      "1 cup Radish (Labanos, sliced diagonally)",
      "1 medium Eggplant (sliced diagonally)",
      "5 to 8 pieces Okra",
      "1 bunch Sitaw (String Beans, cut into 2-inch lengths)",
      "1 bunch Kangkong (leaves and tender stems)",
      "3 pieces Siling Haba (Long Green Chili)",
      "2 tbsp Fish Sauce (Patis)",
      "1/4 tsp Ground Black Pepper"
    ],
    steps: [
      "In a large soup pot, boil pork, tomatoes, and onion in 8 cups water, skimming foam, for 45 to 50 minutes until pork is tender.",
      "Add sliced radish, eggplant, okra, string beans, and long green chili; cook for 5 to 7 minutes.",
      "Stir in the Knorr Sinigang sa Sampaloc Mix and season with fish sauce to taste.",
      "Turn off the heat, fold in fresh kangkong leaves, cover for 2 minutes to steam, and serve hot."
    ],
  },
  {
    id: 4,
    name: "Sinigang na Hipon",
    fname: "Shrimp in Tamarind Soup",
    cats: ["Seafood", "Soup"],
    diff: "Beginner",
    minutes: 30,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Sinigang+na+Hipon",
    desc: "A classic Filipino sour soup featuring fresh shrimp, Knorr Sinigang mix, radish, eggplant, okra, sitaw, and fresh kangkong.",
    ing: [
      "Shrimp",
      "Tamarind (Sampalok)",
      "Tomato",
      "Onion",
      "Radish",
      "Eggplant",
      "Okra",
      "Sitaw (String Beans)",
      "Kangkong",
      "Siling Haba (Long Chili)",
      "Fish Sauce (Patis)",
    ],
    ingredientsDetailed: [
      "1 lb Shrimp (cleaned, whiskers trimmed, heads and shells left on)",
      "1 pack (44g) Knorr Sinigang sa Sampaloc Mix",
      "8 cups Water (or Rice Wash / Hugas Bigas)",
      "2 to 3 Tomatoes (quartered)",
      "1 medium Onion (quartered)",
      "1 cup Radish (Labanos, sliced)",
      "1 medium Eggplant (sliced diagonally)",
      "5 to 8 pieces Okra",
      "1 bunch Sitaw (Snake Beans, cut into 2-inch pieces)",
      "1 bunch Kangkong (leaves and tender stalks)",
      "3 pieces Siling Haba (Long Green Chili)",
      "2 tbsp Fish Sauce (Patis)",
      "1/4 tsp Ground Black Pepper"
    ],
    steps: [
      "In a cooking pot, bring water (or rice wash) to a boil with quartered onions, tomatoes, and sliced radish. Cover and simmer for 8 minutes.",
      "Add the cleaned shrimp to the pot and cook for 1 minute until they begin to turn pink.",
      "Stir in the Knorr Sinigang sa Sampaloc Mix until fully dissolved.",
      "Add the long green chili (siling haba), string beans (sitaw), okra, and sliced eggplant. Simmer for 3 to 5 minutes until vegetables are tender-crisp.",
      "Turn off the heat, fold in the kangkong leaves and stalks, season with fish sauce to taste, cover for 2 minutes to wilt, and serve hot over rice."
    ],
  },
  {
    id: 5,
    name: "Kare-Kare",
    fname: "Kare-Kareng Baka",
    cats: ["Beef", "Stew"],
    diff: "Advanced",
    minutes: 120,
    serves: 6,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Kare-Kare",
    desc: "Tender beef shank or oxtail simmered in a rich, nutty peanut and annatto sauce, served with eggplant, sitaw, pechay, and savory bagoong.",
    ing: ["Beef", "Peanut Butter", "Eggplant", "Sitaw (String Beans)", "Pechay (Bok Choy)", "Shrimp Paste (Bagoong)", "Garlic", "Onion"],
    ingredientsDetailed: [
      "2 lbs Beef Shank or Oxtail (cut into 2-inch pieces)",
      "3/4 cup Peanut Butter (creamy)",
      "1 bunch Pechay (Bok Choy, rinsed)",
      "2 medium Eggplant (sliced diagonally)",
      "1 bunch Sitaw (String Beans, cut into 2-inch lengths)",
      "3 tbsp Shrimp Paste (Bagoong Alamang, sautéed)",
      "1 tbsp Annatto Powder (Atsuete, dissolved in 3 tbsp warm water)",
      "4 cloves Garlic (minced)",
      "1 medium Onion (chopped)",
      "3 cups Reserved Beef Broth"
    ],
    steps: [
      "In a large pot, simmer beef in water with onion for 90 to 120 minutes until fork-tender. Reserve 3 cups of the broth.",
      "In a separate pan, sauté garlic and onion, then add the tender beef pieces and annatto water for color.",
      "Pour in reserved beef broth and bring to a simmer.",
      "Whisk in peanut butter until completely dissolved into a velvety, luscious sauce.",
      "Add eggplant and string beans; cook 5 minutes. Fold in pechay in the final 2 minutes. Serve hot with sautéed bagoong."
    ],
  },
  {
    id: 6,
    name: "Beef Caldereta",
    fname: "Kalderetang Baka",
    cats: ["Beef", "Stew"],
    diff: "Intermediate",
    minutes: 90,
    serves: 6,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Kalderetang+Baka",
    desc: "A rich and savory tomato beef stew enriched with liver spread, hearty potatoes, carrots, and sweet bell peppers.",
    ing: ["Beef", "Tomato Sauce", "Potato", "Carrots", "Bell Pepper", "Liver Spread", "Garlic", "Onion"],
    ingredientsDetailed: [
      "2 lbs Beef Chuck or Short Ribs (cut into 1 1/2-inch cubes)",
      "1 can (85g) Liver Spread",
      "1 cup Tomato Sauce",
      "2 medium Potatoes (cubed)",
      "2 medium Carrots (sliced into rounds)",
      "1 large Bell Pepper (red and green, sliced into strips)",
      "4 cloves Garlic (minced)",
      "1 medium Onion (chopped)",
      "2 cups Water or Beef Broth",
      "1/2 cup Green Peas (optional)"
    ],
    steps: [
      "Sear beef cubes in hot oil until browned on all sides, then remove.",
      "Sauté garlic and onion in the drippings until fragrant, then return beef.",
      "Pour in tomato sauce and 2 cups broth. Cover and simmer on low heat for 60 to 75 minutes until meat is tender.",
      "Stir in the liver spread until fully incorporated into the rich sauce.",
      "Add potatoes, carrots, and bell pepper; simmer for 12 to 15 minutes until vegetables are tender and sauce is thick."
    ],
  },
  {
    id: 7,
    name: "Chicken Tinola",
    fname: "Tinolang Manok",
    cats: ["Chicken", "Soup"],
    diff: "Beginner",
    minutes: 45,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/tinolang-manok-recipe/",
    desc: "A warm, gingery chicken soup simmered with sayote wedges and fresh malunggay leaves.",
    ing: ["Chicken", "Ginger", "Sayote (Chayote)", "Malunggay", "Fish Sauce (Patis)", "Onion", "Garlic"],
    ingredientsDetailed: [
      "2 lbs Chicken (cut into serving pieces)",
      "2 thumbs Ginger (julienned)",
      "1 medium Sayote (Chayote, peeled and wedged)",
      "1 cup Malunggay (fresh leaves)",
      "2 tbsp Fish Sauce (Patis)",
      "1 medium Onion (sliced)",
      "4 cloves Garlic (minced)",
      "5 cups Water or Rice Washing"
    ],
    steps: [
      "Sauté ginger, garlic, and onion in a pot until aromatic.",
      "Add chicken and fish sauce; sear for 3 to 5 minutes until chicken is lightly browned.",
      "Pour in 5 cups water. Bring to a boil, skim foam, cover and simmer for 25 minutes.",
      "Add sayote wedges and cook for 6 minutes until edges are tender.",
      "Turn off heat, stir in malunggay leaves, cover for 2 minutes, and serve with hot rice."
    ],
  },
  {
    id: 8,
    name: "Bicol Express",
    fname: "Bicol Express",
    cats: ["Pork", "Stew"],
    diff: "Intermediate",
    minutes: 45,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Bicol+Express",
    desc: "Pork belly slow-simmered in rich coconut milk and coconut cream with sautéed shrimp paste and spicy green chilies.",
    ing: [
      "Pork Belly",
      "Coconut Milk (Gata)",
      "Shrimp Paste (Bagoong)",
      "Siling Haba (Long Chili)",
      "Onion",
      "Garlic",
      "Ginger",
    ],
    ingredientsDetailed: [
      "2 lbs Pork Belly (sliced into bite-sized strips)",
      "2 cups Coconut Milk (Gata)",
      "1 cup Coconut Cream (Kakang Gata)",
      "2 tbsp Shrimp Paste (Bagoong Alamang)",
      "6 to 8 pcs Siling Haba (Long Green Chili, sliced)",
      "1 medium Onion (chopped)",
      "4 cloves Garlic (minced)",
      "1 thumb Ginger (minced)",
      "1/2 cup Water"
    ],
    steps: [
      "Sear sliced pork belly in a pan until lightly browned and natural oils render.",
      "Sauté garlic, onion, and ginger in the rendered fat until softened and fragrant.",
      "Stir in the shrimp paste and cook for 1 minute to release its aroma.",
      "Pour in coconut milk and water; simmer uncovered for 20 to 25 minutes until pork is tender.",
      "Pour in coconut cream and add sliced green chilies; simmer for 10 minutes until thick and coconut oil begins to separate."
    ],
  },
  {
    id: 9,
    name: "Chicken Curry",
    fname: "Pinoy Chicken Curry",
    cats: ["Chicken", "Stew"],
    diff: "Beginner",
    minutes: 50,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Chicken+Curry",
    desc: "A mild Filipino coconut curry with tender chicken, potatoes, carrots, ginger, and sweet bell peppers.",
    ing: ["Chicken", "Coconut Milk (Gata)", "Potato", "Carrots", "Bell Pepper", "Curry Powder", "Ginger", "Garlic", "Onion"],
    ingredientsDetailed: [
      "2 lbs Chicken (cut into serving pieces)",
      "1 1/2 cups Coconut Milk (Gata)",
      "2 tbsp Curry Powder",
      "2 medium Potatoes (cubed)",
      "1 large Carrot (sliced into rounds)",
      "1 medium Bell Pepper (red and green, cubed)",
      "1 thumb Ginger (minced)",
      "4 cloves Garlic (minced)",
      "1 medium Onion (chopped)",
      "2 tbsp Fish Sauce (Patis)",
      "1/2 cup Water"
    ],
    steps: [
      "Pan-fry potato and carrot cubes in oil until edges are golden, then set aside.",
      "Brown chicken pieces in the pan on all sides, then remove.",
      "Sauté garlic, onion, and ginger, add curry powder, and toast for 30 seconds until fragrant.",
      "Return chicken with coconut milk and 1/2 cup water. Simmer covered on medium-low for 20 minutes.",
      "Add fried potatoes, carrots, and bell peppers; season with fish sauce and simmer 5 minutes until sauce is thick and savory."
    ],
  },
  {
    id: 10,
    name: "Beef Nilaga",
    fname: "Nilagang Baka",
    cats: ["Beef", "Soup"],
    diff: "Beginner",
    minutes: 90,
    serves: 6,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Nilagang+Baka",
    desc: "A clear, restorative broth of slow-boiled beef shank with cabbage, potatoes, sweet corn, and whole peppercorns.",
    ing: ["Beef", "Cabbage", "Potato", "Corn", "Onion", "Fish Sauce (Patis)"],
    ingredientsDetailed: [
      "2 lbs Beef Shank or Beef Brisket (with bone)",
      "1/2 head Cabbage (cut into wedges)",
      "2 medium Potatoes (quartered)",
      "2 ears Sweet Corn (cut into 3 pieces each)",
      "1 large Onion (quartered)",
      "3 tbsp Fish Sauce (Patis)",
      "8 cups Water (or Rice Wash)",
      "1 tsp Whole Peppercorn"
    ],
    steps: [
      "Place beef and quartered onion in a large pot with 8 cups water. Bring to a boil and skim off all foam.",
      "Lower heat, cover, and simmer for 75 to 90 minutes until beef is melt-in-your-mouth tender.",
      "Season with fish sauce and whole peppercorns, add sweet corn and potatoes, and cook for 12 to 15 minutes.",
      "Add cabbage wedges and cook for 3 minutes until tender-crisp.",
      "Ladle broth and beef into bowls and serve hot with calamansi and fish sauce dip."
    ],
  },
  {
    id: 11,
    name: "Pork Menudo",
    fname: "Pork Menudo",
    cats: ["Pork", "Stew"],
    diff: "Intermediate",
    minutes: 60,
    serves: 6,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Pork+Menudo",
    desc: "Diced pork and pork liver stewed in tomato sauce with tender potatoes, carrots, and sweet bell peppers cut to uniform cubes.",
    ing: ["Pork", "Tomato Sauce", "Potato", "Carrots", "Bell Pepper", "Garlic", "Onion", "Soy Sauce", "Calamansi"],
    ingredientsDetailed: [
      "2 lbs Pork Shoulder or Belly (diced into 1/2-inch cubes)",
      "1/4 lb Pork Liver (diced into 1/2-inch cubes)",
      "1 cup Tomato Sauce",
      "2 medium Potatoes (diced into 1/2-inch cubes)",
      "2 medium Carrots (diced into 1/2-inch cubes)",
      "1 medium Bell Pepper (red and green, diced)",
      "1/4 cup Raisins (optional)",
      "4 cloves Garlic (minced)",
      "1 medium Onion (chopped)",
      "2 tbsp Soy Sauce",
      "2 pcs Calamansi (juice extracted)"
    ],
    steps: [
      "Marinate diced pork in soy sauce and calamansi juice for 15 to 30 minutes.",
      "Sauté garlic and onion in oil, add marinated pork, and sear until lightly browned.",
      "Pour in tomato sauce and 1 cup water. Simmer covered for 30 minutes until meat is tender.",
      "Add diced liver, potatoes, and carrots; cook for 10 minutes until vegetables are tender.",
      "Stir in diced bell peppers and raisins, simmer for 3 minutes, and season to taste."
    ],
  },
  {
    id: 12,
    name: "Chicken Afritada",
    fname: "Afritadang Manok",
    cats: ["Chicken", "Stew"],
    diff: "Beginner",
    minutes: 50,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Chicken+Afritada",
    desc: "Tender chicken braised in rich tomato sauce with hearty potatoes, carrots, green peas, and bell pepper strips.",
    ing: ["Chicken", "Tomato Sauce", "Potato", "Carrots", "Bell Pepper", "Garlic", "Onion", "Bay Leaf (Laurel)"],
    ingredientsDetailed: [
      "2 lbs Chicken (cut into serving pieces)",
      "1 cup Tomato Sauce",
      "2 medium Potatoes (cubed)",
      "1 large Carrot (sliced into rounds)",
      "1 medium Bell Pepper (red and green, sliced into strips)",
      "1/2 cup Green Peas",
      "2 pcs Dried Bay Leaves",
      "4 cloves Garlic (minced)",
      "1 medium Onion (chopped)",
      "1 cup Chicken Broth or Water"
    ],
    steps: [
      "Pan-fry potatoes and carrots until lightly browned, then set aside.",
      "Sear chicken pieces in the pan until golden on all sides, then remove.",
      "Sauté garlic and onion until soft, return chicken, and pour in tomato sauce, broth, and bay leaves.",
      "Simmer covered for 20 minutes until chicken is tender.",
      "Add potatoes, carrots, bell peppers, and green peas; simmer for 5 minutes until vegetables are tender and sauce is thick."
    ],
  },
  {
    id: 13,
    name: "Ginataang Gulay",
    fname: "Ginataang Kalabasa at Sitaw",
    cats: ["Vegetable", "Stew"],
    diff: "Beginner",
    minutes: 30,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Ginataang+Kalabasa",
    desc: "Squash and snake beans simmered gently in coconut milk with shrimp paste until creamy, savory, and naturally sweet.",
    ing: ["Kalabasa (Squash)", "Sitaw (String Beans)", "Coconut Milk (Gata)", "Shrimp Paste (Bagoong)", "Garlic", "Onion"],
    ingredientsDetailed: [
      "3 cups Kalabasa (Squash, peeled and cubed)",
      "1 bunch Sitaw (Snake Beans, cut into 2-inch lengths)",
      "2 cups Coconut Milk (Gata)",
      "1/2 lb Pork Belly (sliced into small strips, optional)",
      "2 tbsp Shrimp Paste (Bagoong Alamang)",
      "4 cloves Garlic (minced)",
      "1 medium Onion (sliced)",
      "1 pc Siling Haba (Long Green Chili)"
    ],
    steps: [
      "In a pot, sear pork belly strips until lightly browned and fat renders.",
      "Sauté garlic and onion in the drippings, then stir in shrimp paste for 1 minute.",
      "Pour in coconut milk and bring to a gentle simmer over medium-low heat.",
      "Add squash cubes and siling haba, cover, and cook for 8 to 10 minutes until squash softens.",
      "Add string beans and simmer for 5 minutes until tender-crisp. Mash a couple squash cubes to thicken sauce."
    ],
  },
  {
    id: 14,
    name: "Laing",
    fname: "Bicolano Laing",
    cats: ["Vegetable", "Stew"],
    diff: "Intermediate",
    minutes: 60,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Laing",
    desc: "Dried taro leaves slow-cooked in coconut milk and coconut cream with shrimp paste, pork, and spicy chilies until silky and velvety.",
    ing: [
      "Taro Leaves (Dahon ng Gabi)",
      "Coconut Milk (Gata)",
      "Shrimp Paste (Bagoong)",
      "Siling Haba (Long Chili)",
      "Pork Belly",
      "Garlic",
      "Onion",
      "Ginger",
    ],
    ingredientsDetailed: [
      "3.5 oz Taro Leaves (Dahon ng Gabi, dried)",
      "3 cups Coconut Milk (Gata)",
      "1 cup Coconut Cream (Kakang Gata)",
      "1/2 lb Pork Belly (sliced into small cubes)",
      "2 tbsp Shrimp Paste (Bagoong Alamang)",
      "6 pcs Siling Haba (Long Green Chili, sliced)",
      "4 cloves Garlic (minced)",
      "1 medium Onion (chopped)",
      "1 thumb Ginger (minced)"
    ],
    steps: [
      "In a large pot, combine pork belly, coconut milk, garlic, onion, ginger, and shrimp paste; bring to a boil.",
      "Place dried taro leaves on top and press gently into the liquid. Do NOT stir for the first 20 minutes.",
      "Simmer covered on low heat for 30 to 40 minutes until leaves absorb the coconut milk and soften.",
      "Pour in coconut cream and add sliced green chilies; gently stir and simmer until coconut oil separates and sauce is rich."
    ],
  },
  {
    id: 15,
    name: "Pinakbet",
    fname: "Pinakbet Tagalog",
    cats: ["Vegetable", "Stew"],
    diff: "Beginner",
    minutes: 40,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Pinakbet",
    desc: "A native-vegetable medley of squash, eggplant, okra, sitaw, and bitter gourd simmered with pork belly in savory shrimp paste.",
    ing: [
      "Pork Belly",
      "Kalabasa (Squash)",
      "Eggplant",
      "Sitaw (String Beans)",
      "Ampalaya (Bitter Gourd)",
      "Okra",
      "Shrimp Paste (Bagoong)",
      "Tomato",
      "Onion",
      "Garlic",
    ],
    ingredientsDetailed: [
      "1/2 lb Pork Belly (sliced into bite-sized pieces)",
      "2 cups Kalabasa (Squash, cubed)",
      "1 medium Eggplant (sliced diagonally)",
      "1 bunch Sitaw (String Beans, cut into 2-inch lengths)",
      "1 medium Ampalaya (Bitter Gourd, seeded and sliced)",
      "6 pcs Okra (sliced diagonally)",
      "2 tbsp Shrimp Paste (Bagoong Alamang)",
      "2 medium Tomatoes (chopped)",
      "1 medium Onion (chopped)",
      "4 cloves Garlic (minced)",
      "1 cup Water"
    ],
    steps: [
      "Sear pork belly in a pot until golden and fat renders.",
      "Sauté garlic, onion, and tomatoes in the rendered fat until tomatoes soften.",
      "Add squash cubes and shrimp paste dissolved in 1 cup water; cover and cook for 5 minutes.",
      "Add eggplant, string beans, okra, and ampalaya. Cover and steam on medium-low for 8 to 10 minutes without stirring.",
      "Gently toss or shake the pot to coat all vegetables evenly until tender-crisp."
    ],
  },
  {
    id: 16,
    name: "Grilled Bangus",
    fname: "Inihaw na Bangus",
    cats: ["Seafood"],
    diff: "Beginner",
    minutes: 25,
    serves: 2,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Inihaw+na+Bangus",
    desc: "Milkfish stuffed with juicy tomatoes, onions, and ginger, grilled until smoky with charred skin.",
    ing: ["Bangus", "Calamansi", "Soy Sauce", "Onion", "Tomato", "Ginger", "Garlic"],
    ingredientsDetailed: [
      "1 large Bangus (Milkfish, butterflied and cleaned)",
      "2 medium Tomatoes (diced)",
      "1 medium Onion (diced)",
      "1 thumb Ginger (minced)",
      "3 pcs Calamansi (juice extracted)",
      "2 tbsp Soy Sauce",
      "3 cloves Garlic (minced)"
    ],
    steps: [
      "Marinate cleaned bangus in calamansi juice, soy sauce, and garlic for 20 minutes.",
      "In a bowl, mix diced tomatoes, onions, and ginger, then stuff evenly into the fish cavity.",
      "Wrap fish securely in aluminum foil or banana leaf.",
      "Grill over medium hot coals for 8 to 10 minutes per side.",
      "Open foil in the final 2 minutes to char skin directly over coals. Serve hot with spiced toyomansi."
    ],
  },
  {
    id: 17,
    name: "Ginisang Monggo",
    fname: "Ginisang Munggo",
    cats: ["Pork", "Soup", "Vegetable"],
    diff: "Beginner",
    minutes: 45,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Ginisang+Monggo",
    desc: "A hearty mung bean stew with pork belly, fresh malunggay leaves, and savory chicharon topping.",
    ing: ["Mung Beans (Monggo)", "Pork Belly", "Malunggay", "Tomato", "Onion", "Garlic", "Fish Sauce (Patis)"],
    ingredientsDetailed: [
      "1 cup Mung Beans (Monggo, rinsed)",
      "1/2 lb Pork Belly (diced into small cubes)",
      "1 cup Malunggay (fresh leaves)",
      "1/2 cup Chicharon (crushed, for topping)",
      "2 medium Tomatoes (chopped)",
      "1 medium Onion (chopped)",
      "4 cloves Garlic (minced)",
      "2 tbsp Fish Sauce (Patis)",
      "4 to 5 cups Water"
    ],
    steps: [
      "In a pot, boil mung beans in 4 cups water for 30 to 35 minutes until completely soft and skins burst.",
      "In another pan, sauté garlic, onion, and tomatoes, then add diced pork belly and cook until browned.",
      "Season pork with fish sauce and cook until tomatoes break down into a sauce.",
      "Pour sautéed pork into the boiled mung beans pot and simmer together for 10 minutes.",
      "Add fresh malunggay leaves, cover for 2 minutes off the heat, and top with crushed chicharon before serving."
    ],
  },
  {
    id: 18,
    name: "Crispy Pata",
    fname: "Crispy Pata",
    cats: ["Pork"],
    diff: "Advanced",
    minutes: 90,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Crispy+Pata",
    desc: "Pork hock slow-boiled with aromatics until tender, air-dried, and deep-fried to a golden shatteringly crisp skin.",
    ing: ["Pork Belly", "Garlic", "Bay Leaf (Laurel)", "Soy Sauce", "Vinegar", "Onion"],
    ingredientsDetailed: [
      "1 whole Pork Hock / Leg (or 2.5 lbs Pork Belly slab, cleaned)",
      "1 head Garlic (crushed)",
      "4 pcs Dried Bay Leaves",
      "2 tbsp Soy Sauce",
      "2 tbsp Vinegar",
      "1 large Onion (quartered)",
      "1 tbsp Salt",
      "1 tsp Whole Peppercorn"
    ],
    steps: [
      "Boil pork hock in a large pot with garlic, bay leaves, onion, salt, and peppercorns for 60 to 75 minutes until tender.",
      "Drain well and air-dry pork completely in the refrigerator for 3+ hours or overnight for maximum crispiness.",
      "Deep-fry in hot oil (350°F / 175°C) using a splatter shield for 8 to 10 minutes until skin puffs and blisters into a golden crunch.",
      "Rest on a wire rack for 5 minutes.",
      "Chop and serve with spiced vinegar and soy sauce dipping sauce."
    ],
  },
  {
    id: 19,
    name: "Chopsuey",
    fname: "Pinoy Chopsuey",
    cats: ["Vegetable", "Seafood", "Stew"],
    diff: "Beginner",
    minutes: 30,
    serves: 4,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Chopsuey",
    desc: "A colorful, crisp stir-fry of cabbage, carrots, cauliflower, snow peas, bell pepper, and shrimp in a savory oyster sauce glaze with quail eggs.",
    ing: ["Cabbage", "Carrots", "Bell Pepper", "Shrimp", "Oyster Sauce", "Garlic", "Onion"],
    ingredientsDetailed: [
      "1/2 lb Shrimp (peeled and deveined)",
      "2 cups Cabbage (chopped into bite-sized squares)",
      "1 medium Carrot (sliced diagonally)",
      "1 cup Cauliflower (cut into small florets)",
      "1/2 cup Snow Peas (Chicharo, trimmed)",
      "1 medium Bell Pepper (red and green, sliced)",
      "6 pcs Quail Eggs (hard-boiled and peeled)",
      "2 tbsp Oyster Sauce",
      "4 cloves Garlic (minced)",
      "1 medium Onion (chopped)",
      "1/2 cup Water"
    ],
    steps: [
      "Sear shrimp in a hot wok for 1 to 2 minutes until pink, then remove and set aside.",
      "Sauté garlic and onion in the wok until fragrant.",
      "Add carrots, cauliflower, snow peas, bell peppers, and 1/2 cup water; cover and steam for 3 minutes.",
      "Add cabbage and oyster sauce, tossing briskly over high heat for 2 minutes.",
      "Return shrimp and add boiled quail eggs, toss gently for 1 minute, and serve immediately while vegetables stay crunchy."
    ],
  },
  {
    id: 20,
    name: "Sinigang na Baka",
    fname: "Beef Sinigang",
    cats: ["Beef", "Soup"],
    diff: "Intermediate",
    minutes: 110,
    serves: 6,
    source: "Panlasang Pinoy",
    recipeUrl: "https://panlasangpinoy.com/?s=Sinigang+na+Baka",
    desc: "A deeply comforting sour broth built on beef short ribs simmered until melt-in-your-mouth tender with fresh vegetables.",
    ing: [
      "Beef",
      "Tamarind (Sampalok)",
      "Tomato",
      "Onion",
      "Sitaw (String Beans)",
      "Kangkong",
      "Radish",
      "Eggplant",
      "Okra",
      "Siling Haba (Long Chili)",
      "Fish Sauce (Patis)",
    ],
    ingredientsDetailed: [
      "2 lbs Beef Short Ribs (or beef brisket, cut into chunks)",
      "1 pack (44g) Knorr Sinigang sa Sampaloc Mix",
      "8 cups Water",
      "2 medium Tomatoes (quartered)",
      "1 large Onion (quartered)",
      "1 cup Radish (Labanos, sliced diagonally)",
      "1 medium Eggplant (sliced diagonally)",
      "5 to 8 pieces Okra",
      "1 bunch Sitaw (String Beans, cut into 2-inch lengths)",
      "1 bunch Kangkong (leaves and tender stems)",
      "3 pieces Siling Haba (Long Green Chili)",
      "2 tbsp Fish Sauce (Patis)",
      "1/4 tsp Ground Black Pepper"
    ],
    steps: [
      "Boil beef chunks in 8 cups water, skimming all scum, and add quartered tomatoes and onion.",
      "Simmer covered on low heat for 75 to 90 minutes until beef short ribs pull tenderly from the bone.",
      "Add sliced radish, eggplant, okra, string beans, and siling haba; cook for 5 to 7 minutes.",
      "Stir in Knorr Sinigang sa Sampaloc Mix and season with fish sauce to taste.",
      "Turn off heat, add kangkong, cover for 2 minutes to wilt, and serve hot over steamed rice."
    ],
  },
]

/** Reverse index: ingredient name -> group, built once at module load. */
export const INGREDIENT_TO_GROUP = Object.entries(INGREDIENT_GROUPS).reduce((acc, [group, items]) => {
  for (const item of items) acc[item] = group
  return acc
}, {})